FROM python:3.11-slim
 
WORKDIR /app
 
RUN pip install uv
 
COPY pyproject.toml uv.lock ./
 
RUN uv sync
 
COPY Scripts ./Scripts
COPY eq_models ./eq_models
 
RUN mkdir -p ./modelos_globales
 
EXPOSE 8025
 
CMD ["python", "Scripts/model_sender.py"]
 